### ISSUE TITLE
Errors defined in nansat.tools

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansat#186] opened 2017-03-14 11:19 UTC
The nansat.tools module provides a set of errors that are specific to Nansat but their naming make them appear as general python errors. I suggest to change the names, e.g., to ```NansatOptionError``` instead of ```OptionError```, or completely rethink the error handling.

**Comment by akorosov** [comment] 2017-12-14 12:51
Duplicate of #179

**Closed by akorosov** 2017-12-14 12:51 UTC
Labels: duplicate, enhancement
