### ISSUE TITLE
Update hotfix documentation

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#239] opened 2018-02-02 09:27 UTC
Add small note on step 4.4 in the workflow: wait for tests to pass before merging.

Last follow up from #222. But this does not require a hotfix.

**Comment by aleksandervines** [comment] 2018-02-02 09:30
See comment in #238

**Comment by akorosov** [comment] 2018-03-07 14:22
Duplicate of #272

**Closed by akorosov** 2018-03-07 14:22 UTC
Labels: documentation, duplicate, good first issue
