### ISSUE TITLE
Reduce number of branches

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#200] opened 2017-12-14 13:11 UTC
#### Problem There are too many branches. Some branches are wrongly branched from other issue branches, some are obsolete #### Solution Remove old branches

**Comment by aleksandervines** [comment] 2018-01-17 12:37
I suggest to remove:

- the two branches for issue 54. issue 54 has been closed as "wontfix".
- branches for issues 63/66/70/71/72/74/75/77/79/81/82/84/86/92/106/114/115/117/118/119/156/157 - issues have been closed and all commits merged into develop or master.
- pythesint/add_mapper_tests - not sure what these branches is, but it does not contain anything not in master

**Comment by mortenwh** [comment] 2018-01-17 14:49
Points 1 and 2 ok with me. Is the last point about nansat? Can you add a link?

Apart from that, I am unsure about what to do with the branch issue113-get_transect-reverted-for-qp-paper - this is a version that was used for a paper which is now published. The last commit is 0f8ffa3c9a5185802e432af7fc9fb875995a378c - as long as the hash code is (now) logged I guess the branch can be deleted, right?

**Comment by aleksandervines** [comment] 2018-01-17 14:51
point 3 is about 2 branches in nansat, one names pythesint and one named add_mapper_tests :) I can see the confusion in how I wrote it.

**Comment by aleksandervines** [comment] 2018-01-17 15:27
I further suggest to remove these branches, they are some commits ahead of master/develop, but that could be due to "wrong" git usage during the merge. 

- issue 60 branches, it is regarding issue 60 about online documentation, which is closed. It says it is 10 commits behind master, but this must be outdated (3-4 years old), we are currently updating the online documentation. Last commits in each branch 0ceacc6c6bc7296a9f0a7ecfa33135434f2b9cb8 fcbe0ea8efcaa46d9e5e33e4fb17f3b6939f7633 23b66509ff608772123b879470ecc903bdff3d1a
- issue 76 branch. The issue is closed. I assume that any relevant stuff has been merged, and in either case last commit: db0f3c5477ef497bfa1082b749201ab4250597cd
- issue 99 brances. Issue closed and merged in bb9aa96adead0eba7a44550fd318e132d8fc3211 last commits: a37c8f69b599eea1e275b16282b5106b0de57682 7bd4e2f91b1cce0a2e67a4c86d2a008078799b7d
- issue 113 branch. Issue closed. last commit: 0f8ffa3c9a5185802e432af7fc9fb875995a378c
- test-pyqt. Not directly connect to an issue. The only modification done in this is in the travis configuration, removing specific qt version pinning. This branch seems useless now, as I assume the only use of it was to see how travis behaved.

**Comment by akorosov** [comment] 2018-01-18 16:42
All of these branches can be deleted. Thanks, @alevin!

**Comment by aleksandervines** [comment] 2018-01-19 12:51
Everything above is deleted.

Comments on remaining stale branches:

- issue91-nansattest - There seems to be tests here that might be useful to merge into develop. https://github.com/nansencenter/nansat/compare/develop...issue91-nansattest should be reviwed and parts merged as a part of #91 
- issue123-fillValue Might contain useful code for #123 but I think this reference should do and we can **delete the branch** as a lot of the code has probably changed since. Last/only commit: 42cad4f92f097c405ce21d9b8ccbced470efbaab this commit is also in #42 
- issue39-SARcomplexdata hard to say for me
- issue98-legendImage newer version is in issue98-legendImage-develop, so **issue98-legendImage can safely be deleted**
- issue98-legendImage-develop seems useful for #98
- issue58-update newer version is in issue58-update-develop, so **issue58-update can safely be deleted**
-  issue58-update-develop looks useful for #58
- issue42 - looks useful for #42 
- dev_doppler_vm @mortenwh

**Comment by akorosov** [comment] 2018-01-24 07:49
* issue91-nansattest - is outdated and can be deleted.
* issue123-fillValue -  I agree with @aleksandervines 
* issue39-SARcomplexdata - is outdated and can be deleted.
* issue98-legendImage - I agree with @aleksandervines 
* issue98-legendImage-develop - has wrong implementation. Can be deleted.
* issue58-update - I agree with @aleksandervines 
* issue58-update-develop - is outdated and can be deleted.
* issue42 - is outdated and can be deleted.

**Comment by aleksandervines** [comment] 2018-01-24 08:27
Will delete them. 
Last one, @mortenwh - dev_doppler_vm ?

**Comment by mortenwh** [comment] 2018-01-24 09:42
I have now deleted the branch dev_doppler_vm

**Comment by aleksandervines** [comment] 2018-01-24 10:26
Everything should now be cleaned up. It should be no need to merge any branches, as previously suggested. 

For reference for #42 this is the last commit in the deleted issue42 branch. 2749467035b590b2e621794b4bba3f6e9bb742e8

**Closed** 2018-01-24 10:30 UTC
Labels: enhancement
